# Generated by Django 5.2.7 on 2025-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
