# Generated by Django 5.2.7 on 2025-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizhistory_current_question_index_quizhistory_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='user_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
