# Generated by Django 5.2.7 on 2026-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quizhistory_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='time_left',
            field=models.IntegerField(default=30),
        ),
    ]
