# Generated by Django 5.2.7 on 2026-02-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # EmailOTP model removed; migration left empty for existing initial migration.
    ]
